POST http://localhost:8080/post
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhdWdhdEBnbWFpbC5jb20iLCJleHAiOjE3NTc5NzYzMzIsInVzZXJJZCI6MX0.lieFJzeTr-R6NzwFClpLgQUs3XB78sj_EuIo9uLbN-Y

{
    "content": "Coding a million dollar startup!"
}