DELETE http://localhost:8080/post/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhdWdhdEBnbWFpbC5jb20iLCJleHAiOjE3NTc2OTkyMzQsInVzZXJJZCI6MX0.7GzQcSvxdNd22aMgjxd1VPtYLONXv5nANjHTNadRN3s