POST http://localhost:8080/follow/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1ZmZ5QGdtYWlsLmNvbSIsImV4cCI6MTc1Nzk3NTM3NCwidXNlcklkIjozfQ.3KLpnQpvIWQFkMeZxPiCn8KzrB3QRed6tqOSFG8fEKs