POST http://localhost:8080/follow/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imhlcm9AZ21haWwuY29tIiwiZXhwIjoxNzU3NzUzNTkzLCJ1c2VySWQiOjJ9.qhd9gktRUBQSJucMs7WoEQsske0RrJmodwnA5SbILzc