POST http://localhost:8080/follow/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imhlcm9AZ21haWwuY29tIiwiZXhwIjoxNzU3ODM2Mjc2LCJ1c2VySWQiOjJ9.PXxY-2NjiOozHx66Fq3ZGtMzB4SEOOaF-fcDCEIZfBA