GET http://localhost:8080/user/following
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1ZmZ5QGdtYWlsLmNvbSIsImV4cCI6MTc1Nzk3NjA5MywidXNlcklkIjozfQ.0pjLAsV2HhcwKaQzwEKtsQ2hx9d3vMxxUataQL1h4vg